language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
  - install coveralls

# command to run tests
script:
 - nosetests --rednose --with-coverage --cover-package=app -v


after_success:
  - coveralls
