language: python
python:
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install coveralls
  
services:
  - postgresql

before_script:
  - export FLASK_ENV=testing
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
  - psql -c "CREATE DATABASE testing_db;" -U postgres
  - psql -c "CREATE DATABASE ireporter_db;" -U postgres
  -export DATABASE_URL="dbname='Crud' host='localhost' port='5432' user='postgres' password=''"


# command to run tests
script:
 - nosetests --with-coverage --cover-package=app -v


after_success:
  - coveralls
